apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: simple-api
  annotations:
    github.com/project-slug: mathesonbr/simple-api
spec:
  type: other
  lifecycle: unknown
  owner: mathesonbr
