apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-api
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: simple-api
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/Simple-Org-123/simple-api.git
      ref:
        branch: main
